### PR TITLE
add categories to Line Awesome

### PR DESCRIPTION
**Pull request by gabrielsolomon**

### CODE REVIEW

**Comment by cyberalien** [comment]
This cannot be merged because categories cannot be automatically maintained.

Icons are automatically updated. For Line Awesome icon set source is [Line Awesome GitHub repository](https://github.com/icons8/line-awesome). Unfortunately that repository does not contain list of categories and I don't see any other source for up to date categories. Where did you get data for this pull request?

If there is no data for categories, maintained by icon set author, categories cannot be reliably retrieved when icon set is updated. That means if Icons8 add new icons to Line Awesome, categories need to be manually updated. Manual maintenance is not acceptable.

**Comment by gabrielsolomon** [comment]
I did a scripted add, but not based on repo data, that you are right does not exists.

Since they are a Font Awesome replacement, what i did is i took the categories from Font Awesome and just do a search for each icon on the html from their page: https://icons8.com/line-awesome to see the icons exists there, and remove the ones that didn't

**Comment by cyberalien** [comment]
Getting categories from Font Awesome is a good idea! I'll test it

**Comment by cyberalien** [comment]
Added.

Sorry, can't use your pull request. This repository is generated, so code needs to be changed in script that generates this repository. Merging pull request would result in changes being overridden next time icon compiler runs. However thanks a lot for idea, I've made necessary changes to compiler script based on your suggestions.

**Pull request closed without merging**
